/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientsIndexRouteImport } from './routes/clients/index'
import { Route as InvoicesNewRouteImport } from './routes/invoices/new'
import { Route as InvoicesInvoiceIdRouteImport } from './routes/invoices/$invoiceId'
import { Route as ClientsNewRouteImport } from './routes/clients/new'
import { Route as ClientsClientIdRouteImport } from './routes/clients/$clientId'
import { Route as InvoicesInvoiceIdEditRouteImport } from './routes/invoices/$invoiceId/edit'
import { Route as ApiInvoicesInvoiceIdPdfRouteImport } from './routes/api/invoices/$invoiceId/pdf'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesNewRoute = InvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesInvoiceIdRoute = InvoicesInvoiceIdRouteImport.update({
  id: '/invoices/$invoiceId',
  path: '/invoices/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsNewRoute = ClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesInvoiceIdEditRoute = InvoicesInvoiceIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => InvoicesInvoiceIdRoute,
} as any)
const ApiInvoicesInvoiceIdPdfRoute = ApiInvoicesInvoiceIdPdfRouteImport.update({
  id: '/api/invoices/$invoiceId/pdf',
  path: '/api/invoices/$invoiceId/pdf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRouteWithChildren
  '/invoices/new': typeof InvoicesNewRoute
  '/clients/': typeof ClientsIndexRoute
  '/invoices/$invoiceId/edit': typeof InvoicesInvoiceIdEditRoute
  '/api/invoices/$invoiceId/pdf': typeof ApiInvoicesInvoiceIdPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRouteWithChildren
  '/invoices/new': typeof InvoicesNewRoute
  '/clients': typeof ClientsIndexRoute
  '/invoices/$invoiceId/edit': typeof InvoicesInvoiceIdEditRoute
  '/api/invoices/$invoiceId/pdf': typeof ApiInvoicesInvoiceIdPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRouteWithChildren
  '/invoices/new': typeof InvoicesNewRoute
  '/clients/': typeof ClientsIndexRoute
  '/invoices/$invoiceId/edit': typeof InvoicesInvoiceIdEditRoute
  '/api/invoices/$invoiceId/pdf': typeof ApiInvoicesInvoiceIdPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/clients/$clientId'
    | '/clients/new'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/clients/'
    | '/invoices/$invoiceId/edit'
    | '/api/invoices/$invoiceId/pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/clients/$clientId'
    | '/clients/new'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/clients'
    | '/invoices/$invoiceId/edit'
    | '/api/invoices/$invoiceId/pdf'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/clients/$clientId'
    | '/clients/new'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/clients/'
    | '/invoices/$invoiceId/edit'
    | '/api/invoices/$invoiceId/pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  ClientsClientIdRoute: typeof ClientsClientIdRoute
  ClientsNewRoute: typeof ClientsNewRoute
  InvoicesInvoiceIdRoute: typeof InvoicesInvoiceIdRouteWithChildren
  InvoicesNewRoute: typeof InvoicesNewRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  ApiInvoicesInvoiceIdPdfRoute: typeof ApiInvoicesInvoiceIdPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/new': {
      id: '/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof InvoicesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$invoiceId': {
      id: '/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof InvoicesInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/new': {
      id: '/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof ClientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$invoiceId/edit': {
      id: '/invoices/$invoiceId/edit'
      path: '/edit'
      fullPath: '/invoices/$invoiceId/edit'
      preLoaderRoute: typeof InvoicesInvoiceIdEditRouteImport
      parentRoute: typeof InvoicesInvoiceIdRoute
    }
    '/api/invoices/$invoiceId/pdf': {
      id: '/api/invoices/$invoiceId/pdf'
      path: '/api/invoices/$invoiceId/pdf'
      fullPath: '/api/invoices/$invoiceId/pdf'
      preLoaderRoute: typeof ApiInvoicesInvoiceIdPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InvoicesInvoiceIdRouteChildren {
  InvoicesInvoiceIdEditRoute: typeof InvoicesInvoiceIdEditRoute
}

const InvoicesInvoiceIdRouteChildren: InvoicesInvoiceIdRouteChildren = {
  InvoicesInvoiceIdEditRoute: InvoicesInvoiceIdEditRoute,
}

const InvoicesInvoiceIdRouteWithChildren =
  InvoicesInvoiceIdRoute._addFileChildren(InvoicesInvoiceIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  ClientsClientIdRoute: ClientsClientIdRoute,
  ClientsNewRoute: ClientsNewRoute,
  InvoicesInvoiceIdRoute: InvoicesInvoiceIdRouteWithChildren,
  InvoicesNewRoute: InvoicesNewRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  ApiInvoicesInvoiceIdPdfRoute: ApiInvoicesInvoiceIdPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
